<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PantRepository extends EntityRepository
{
    public function createQueryBuilder($alias, $indexBy = null)
    {
        $qb = parent::createQueryBuilder($alias, $indexBy);

        $qb->select($alias, 'f')
            ->leftJoin($alias . '.feature', 'f');

        return $qb;
    }
}
