<?php

namespace AppBundle\Repository;

/**
 * UnderwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnderwareRepository extends PantRepository
{
    public function findAll() {
        return $this->createQueryBuilder('a')
            ->getQuery()
            ->getResult();
    }
}
