<?php

namespace AppBundle\Repository;

/**
 * UnderwareFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnderwareFeatureRepository extends FeatureRepository
{
}
